---
- name: add DM machines to satellite
  hosts: all
  tasks:
  - name: Install Satellite ca
    yum:
      name: http://serhe.com/pub/katello-ca-consumer-latest.noarch.rpm
      state: present
  - name: Register RHEL8  with activationkey
    redhat_subscription:
      state: present
      activationkey: Activation-Key-DM-RHEL8
      org_id: DM
	when: ansible_distribution_major_version == "8"
  - name: Register RHEL7  with activationkey
    redhat_subscription:
      state: present
      activationkey: Activation-Key-DM-RHEL7
      org_id: DM
	when: ansible_distribution_major_version == "7"
  - name: Register RHEL6  with activationkey
    redhat_subscription:
      state: present
      activationkey: Activation-Key-DM-RHEL6
      org_id: DM
	when: ansible_distribution_major_version == "6"
  